<?php
/**
 * You are allowed to use this API in your web application.
 *
 * Copyright (C) 2016 by customweb GmbH
 *
 * This program is licenced under the customweb software licence. With the
 * purchase or the installation of the software in your application you
 * accept the licence agreement. The allowed usage is outlined in the
 * customweb software licence which can be found under
 * http://www.sellxed.com/en/software-license-agreement
 *
 * Any modification or distribution is strictly forbidden. The license
 * grants you the installation in one application. For multiuse you will need
 * to purchase further licences at http://www.sellxed.com/shop.
 *
 * See the customweb software licence agreement for more details.
 *
 *
 * @category	Customweb
 * @package		Customweb_OgoneCw
 * 
 */

/* @var $block \Customweb\OgoneCw\Block\Adminhtml\Transaction\View\Form */
?>

<section class="admin__page-section">
	<div class="admin__page-section-title">
		<span class="title"><?php echo __('Transaction') ?></span>
	</div>
	<div class="admin__page-section-content">
		<div class="admin__page-section-item ogonecw-transaction-information">
            <div class="admin__page-section-item-title">
                <span class="title"><?php echo __('Information') ?></span>
            </div>
            <div class="admin__page-section-item-content">
				<table class="data-table admin__table-secondary">
					<?php foreach($block->getTransaction()->getTransactionObject()->getTransactionLabels() as $label) : ?>
					<tr>
						<th>
							<?php echo $block->escapeHtml($label['label']) ?>
							<?php if (isset($label['description'])) : ?>
								<div class="tooltip"><span class="help"><span></span></span><div class="tooltip-content"><?php echo $block->escapeHtml($label['description']) ?></div></div>
							<?php endif; ?>
						</th>
						<td><?php echo $block->escapeHtml($label['value']) ?></td>
					</tr>
					<?php endforeach; ?>
				</table>
            </div>
        </div>
		<div class="admin__page-section-item ogonecw-transaction-history">
            <div class="admin__page-section-item-title">
                <span class="title"><?php echo __('Transaction History') ?></span>
            </div>
            <div class="admin__page-section-item-content">
				<div class="edit-order-comments">
					<?php foreach(array_reverse($block->getTransaction()->getTransactionObject()->getHistoryItems()) as $historyItem) : ?>
						<ul class="note-list">
							<li class="note-list-item">
								<?php $creationDate = $historyItem->getCreationDate()->format('Y-m-d H:i:s'); ?>
								<span class="note-list-date"><?php echo $block->formatDate($creationDate, \IntlDateFormatter::MEDIUM) ?></span>
								<span class="note-list-time"><?php echo $block->formatTime($creationDate, \IntlDateFormatter::MEDIUM) ?></span>
								<span class="note-list-status"><?php echo $block->escapeHtml(__(ucfirst($historyItem->getActionPerformed()))) ?></span>
								<div class="note-list-comment"><?php echo $block->escapeHtml((string)$historyItem->getMessage()) ?></div>
							</li>
						</ul>
					<?php endforeach; ?>
				</div>
            </div>
        </div>
	</div>
</section>

<section class="admin__page-section">
	<div class="admin__page-section-title">
		<span class="title"><?php echo __('Captures & Refunds') ?></span>
	</div>
	<div class="admin__page-section-content">
		<div class="admin__page-section-item ogonecw-transaction-captures">
            <div class="admin__page-section-item-title">
                <span class="title"><?php echo __('Captures') ?></span>
            </div>
            <div class="admin__page-section-item-content">
				<div class="grid">
					<table class="data-table admin__table-primary ogonecw-transaction-captures-table">
				        <thead>
				            <tr class="headings">
				                <th><span><?php echo __('Date') ?></span></th>
				                <th><span><?php echo __('Amount') ?></span></th>
				                <th><span><?php echo __('Status') ?></span></th>
				            </tr>
				        </thead>
				        <?php $i = 0; foreach ($block->getTransaction()->getTransactionObject()->getCaptures() as $capture) : ?>
				        	<?php $i++; ?>
					        <tbody class="<?php echo $i%2 ? 'even' : 'odd' ?>">
				                <tr>
									<td><?php echo $block->formatDate($capture->getCaptureDate()->format('Y-m-d H:i:s'), \IntlDateFormatter::MEDIUM, true) ?></td>
									<td><?php echo $block->formatPrice($capture->getAmount()) ?></td>
									<td><?php echo __(ucfirst($capture->getStatus())) ?></td>
				                </tr>
							</tbody>
						<?php endforeach; ?>
					</table>
				</div>
			</div>
		</div>
		<div class="admin__page-section-item ogonecw-transaction-refunds">
            <div class="admin__page-section-item-title">
                <span class="title"><?php echo __('Refunds') ?></span>
            </div>
            <div class="admin__page-section-item-content">
				<div class="grid">
					<table class="data-table admin__table-primary ogonecw-transaction-refunds-table">
				        <thead>
				            <tr class="headings">
				                <th><span><?php echo __('Date') ?></span></th>
				                <th><span><?php echo __('Amount') ?></span></th>
				                <th><span><?php echo __('Status') ?></span></th>
				            </tr>
				        </thead>
				        <?php $i = 0; foreach ($block->getTransaction()->getTransactionObject()->getRefunds() as $refund) : ?>
				        	<?php $i++; ?>
					        <tbody class="<?php echo $i%2 ? 'even' : 'odd' ?>">
				                <tr>
									<td><?php echo $block->formatDate($refund->getRefundedDate()->format('Y-m-d H:i:s'), \IntlDateFormatter::MEDIUM, true) ?></td>
									<td><?php echo $block->formatPrice($refund->getAmount()) ?></td>
									<td><?php echo __(ucfirst($refund->getStatus())) ?></td>
				                </tr>
							</tbody>
						<?php endforeach; ?>
					</table>
				</div>
			</div>
		</div>
	</div>
</section>

<?php echo $block->getChildHtml('order_info') ?>